name: Release Workflow

on:
    release:
        types: [published]
    workflow_dispatch:



jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "release done"
