name: Release Workflow

on:
  push:
    branches:
      - 'release*' # Match branches starting with 'release'
      - 'main'

jobs:
  release_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "release done"
